-- Подписки магазинов: платные тарифы, продвижение в витрине, баннеры
-- продавцов и глубокая аналитика.
--
-- Текущее состояние подписки лежит на shops (subscription_plan,
-- subscription_until), а платежи — отдельной таблицей. Разделение не
-- дублирование, а разные режимы чтения: состояние спрашивается на каждом
-- действии продавца и в каждом запросе витрины, и брать его агрегатом
-- max(activated_until) по журналу значило бы платить за это на каждой
-- странице каталога. Журнал же читают редко и целиком — при разборе спора
-- «деньги ушли, подписки нет», где важна каждая строка, включая отменённые.
-- Инвариант между ними один: shops.subscription_until равен максимальному
-- activated_until среди платежей со статусом paid, и он держится тем, что
-- обе записи идут в одной транзакции.
--
-- subscription_credits — вторая колонка рядом с credits_balance, а не общий
-- баланс. Правила жизни у них разные: купленные и подаренные кредиты не
-- сгорают никогда, подписочные обнуляются при выдаче следующего периода.
-- Одной колонкой это не свести — при сгорании пришлось бы вычесть «сколько
-- там было подписочного», а из суммы это уже не узнать. Истёкшая подписка
-- их не сжигает, а запирает: доступность считается выражением
-- USABLE_SUBSCRIPTION_CREDITS (src/db/subscriptions.ts), и оплатив снова,
-- продавец получает ровно норму тарифа — не остатки прошлой и не пустоту.
--
-- Баннеры продавцов встают в существующую banners, отдельной shop_banners
-- нет. Карусель на главной одна, порядок в ней один, общий предел активных
-- баннеров один, а публичный контракт GET /banners клиент уже потребляет.
-- Две таблицы означали бы UNION ALL с двумя разными порядками, два DTO и две
-- ветки в карусели. Цена принятого решения — четыре колонки, вечно пустые у
-- площадочных строк; она меньше. shop_id nullable именно поэтому: пусто —
-- значит баннер площадки, и все уже заведённые строки остаются тем, чем были.
--
-- banners.status по умолчанию 'approved', а не 'pending', потому что дефолт
-- колонки применяется к уже существующим строкам: с 'pending' накат этой
-- миграции уронил бы всю нынешнюю карусель в очередь на проверку, и главная
-- страница осталась бы пустой до тех пор, пока администратор не переодобрит
-- вручную каждый баннер. Продавцу 'pending' ставит код при создании — там,
-- где это осознанное решение, а не побочный эффект ALTER TABLE.
--
-- banners_active_sort_idx удаляется, а не дополняется: ведущим столбцом там
-- был is_active, а он вместе со status ушёл целиком в условие частичного
-- banners_public_idx — отклонённых и ждущих в карусели не бывает вовсе.
--
-- Data-миграции не нужны: все новые колонки на shops, banners, ai_usage и
-- credit_transactions либо имеют DEFAULT, либо nullable. Действующие магазины
-- становятся free с нулевыми счётчиками, действующие баннеры — площадочными
-- и approved. Стартовый период задним числом никому не дарится сознательно.
CREATE TYPE "public"."moderation_status" AS ENUM('pending', 'approved', 'rejected');--> statement-breakpoint
CREATE TYPE "public"."payment_provider" AS ENUM('click', 'payme', 'manual');--> statement-breakpoint
CREATE TYPE "public"."payment_status" AS ENUM('pending', 'prepared', 'paid', 'cancelled', 'failed');--> statement-breakpoint
CREATE TYPE "public"."subscription_plan" AS ENUM('free', 'start', 'pro', 'max');--> statement-breakpoint
CREATE TYPE "public"."subscription_reminder_stage" AS ENUM('expiring_3d', 'expires_today');--> statement-breakpoint
CREATE TABLE "subscription_payments" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"shop_id" bigint NOT NULL,
	"provider" "payment_provider" DEFAULT 'click' NOT NULL,
	"plan" "subscription_plan" NOT NULL,
	"amount" numeric(14, 2) NOT NULL,
	"status" "payment_status" DEFAULT 'prepared' NOT NULL,
	"provider_transaction_id" varchar(64),
	"provider_payment_id" varchar(64),
	"provider_prepare_id" varchar(64),
	"merchant_billing_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "subscription_payments_merchant_billing_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 100000 CACHE 1),
	"activated_from" timestamp with time zone,
	"activated_until" timestamp with time zone,
	"granted_credits" bigint,
	"burned_credits" bigint,
	"paid_at" timestamp with time zone,
	"cancelled_at" timestamp with time zone,
	"initiator_id" bigint,
	"meta" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "subscription_payments_amount_positive" CHECK ("subscription_payments"."amount" > 0)
);
--> statement-breakpoint
CREATE TABLE "subscription_reminders" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"shop_id" bigint NOT NULL,
	"stage" "subscription_reminder_stage" NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"telegram_delivered" boolean DEFAULT false NOT NULL,
	"push_delivered" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shop_search_hits_daily" (
	"shop_id" bigint NOT NULL,
	"day" date NOT NULL,
	"query" varchar(100) NOT NULL,
	"shows" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "shop_search_hits_daily_shop_id_day_query_pk" PRIMARY KEY("shop_id","day","query")
);
--> statement-breakpoint
DROP INDEX "banners_active_sort_idx";--> statement-breakpoint
ALTER TABLE "shops" ADD COLUMN "subscription_plan" "subscription_plan" DEFAULT 'free' NOT NULL;--> statement-breakpoint
ALTER TABLE "shops" ADD COLUMN "subscription_until" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "shops" ADD COLUMN "subscription_credits" bigint DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "shops" ADD COLUMN "autofill_free_used" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "shops" ADD COLUMN "autofill_period_month" date;--> statement-breakpoint
ALTER TABLE "credit_transactions" ADD COLUMN "subscription_after" bigint;--> statement-breakpoint
ALTER TABLE "ai_usage" ADD COLUMN "free" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "banners" ADD COLUMN "shop_id" bigint;--> statement-breakpoint
ALTER TABLE "banners" ADD COLUMN "status" "moderation_status" DEFAULT 'approved' NOT NULL;--> statement-breakpoint
ALTER TABLE "banners" ADD COLUMN "reject_reason" text;--> statement-breakpoint
ALTER TABLE "banners" ADD COLUMN "moderated_by" bigint;--> statement-breakpoint
ALTER TABLE "banners" ADD COLUMN "moderated_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "subscription_payments" ADD CONSTRAINT "subscription_payments_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subscription_payments" ADD CONSTRAINT "subscription_payments_initiator_id_users_id_fk" FOREIGN KEY ("initiator_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subscription_reminders" ADD CONSTRAINT "subscription_reminders_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shop_search_hits_daily" ADD CONSTRAINT "shop_search_hits_daily_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "subscription_payments_provider_txn_idx" ON "subscription_payments" USING btree ("provider","provider_transaction_id");--> statement-breakpoint
CREATE UNIQUE INDEX "subscription_payments_provider_paydoc_idx" ON "subscription_payments" USING btree ("provider","provider_payment_id");--> statement-breakpoint
CREATE UNIQUE INDEX "subscription_payments_merchant_billing_idx" ON "subscription_payments" USING btree ("merchant_billing_id");--> statement-breakpoint
CREATE INDEX "subscription_payments_shop_id_idx" ON "subscription_payments" USING btree ("shop_id","created_at" DESC);--> statement-breakpoint
CREATE INDEX "subscription_payments_status_idx" ON "subscription_payments" USING btree ("status","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "subscription_reminders_once_idx" ON "subscription_reminders" USING btree ("shop_id","stage","expires_at");--> statement-breakpoint
CREATE INDEX "shop_search_hits_shop_day_idx" ON "shop_search_hits_daily" USING btree ("shop_id","day");--> statement-breakpoint
ALTER TABLE "banners" ADD CONSTRAINT "banners_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "banners" ADD CONSTRAINT "banners_moderated_by_users_id_fk" FOREIGN KEY ("moderated_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "shops_subscription_until_idx" ON "shops" USING btree ("subscription_until") WHERE "shops"."subscription_until" IS NOT NULL;--> statement-breakpoint
CREATE INDEX "banners_public_idx" ON "banners" USING btree ("sort_order","id") WHERE "banners"."is_active" AND "banners"."status" = 'approved';--> statement-breakpoint
CREATE INDEX "banners_shop_status_idx" ON "banners" USING btree ("shop_id","status","created_at" DESC);